---

- name: ensure apt-transport-https is installed
  apt:
    name: apt-transport-https
    state: present
  when: ansible_os_family == 'Debian'

- name: install java packages
  package:
    name: '{{ java_packages }}'
    state: present
